# Generated by Django 5.1.7 on 2025-03-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuisnessMarketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_volume', models.IntegerField()),
                ('found_enemies', models.IntegerField()),
                ('market_concentration', models.FloatField()),
                ('market_potential', models.IntegerField()),
                ('available_market', models.FloatField()),
                ('demand_growth', models.FloatField()),
                ('purchasing_power', models.FloatField()),
                ('customer_preferences', models.IntegerField()),
                ('market_penetration_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GoodsMarketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_volume', models.IntegerField()),
                ('found_enemies', models.IntegerField()),
                ('market_concentration', models.FloatField()),
                ('market_potential', models.IntegerField()),
                ('available_market', models.FloatField()),
                ('demand_growth', models.FloatField()),
                ('purchasing_power', models.FloatField()),
                ('customer_preferences', models.IntegerField()),
                ('market_penetration_rate', models.FloatField()),
            ],
        ),
    ]
