# Generated by Django 5.1.7 on 2025-03-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goods_category', models.CharField(max_length=100)),
                ('markets', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(choices=[(0, 'Планируемый'), (1, 'Принятый')], default=0)),
            ],
        ),
    ]
